sudo: false
language: python
python:
      - "3.7"
install:
      - pip install tox 
script:
      - tox
env:
      - TOXENV=py27
      - TOXENV=py35
      - TOXENV=py37
      - TOXENV=pep8

notifications:
      irc: "chat.freenode.net#gabbi"
